# Generated by Django 5.1.5 on 2025-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_number", models.CharField(max_length=7)),
                ("phone_number", models.CharField(max_length=13)),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("department", models.CharField(max_length=50)),
                ("current_year", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("no_of_posts", models.IntegerField(default=0)),
                ("followers", models.IntegerField(default=0)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
