# Generated by Django 5.1.5 on 2025-01-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.SlugField(default="0"),
        ),
    ]
