# Generated by Django 5.1.5 on 2025-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.SlugField(default="@"),
        ),
    ]
