# Generated by Django 5.1.5 on 2025-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hostel",
            field=models.CharField(default="1", max_length=10),
            preserve_default=False,
        ),
    ]
