# Generated by Django 5.1.5 on 2025-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_hostel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="connections",
            field=models.ManyToManyField(blank=True, to="users.user"),
        ),
    ]
